import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#fafafa",
  },
  headerBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingTop: 50,
  },
  headerRight: {
    flexDirection: "row",
    gap: 16,
  },
  container: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 24,
    paddingBottom: 96,
    backgroundColor: "#fafafa",
  },
  centeredRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    marginBottom: 16,
  },
  avatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
    borderWidth: 2,
    borderColor: "#7B7C81",
  },
  billNumber: {
    fontSize: 16,
    color: "#000000",
    fontWeight: "600",
    marginBottom: 8,
  },
  billTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: "#000000",
    lineHeight: 24,
    flexShrink: 1,
  },
  statusRow: {
    flexDirection: "row",
    gap: 12,
  },
  status: {
    fontSize: 14,
    color: "#008CFF",
    fontWeight: "600",
    backgroundColor: "rgba(0, 140, 255, 0.1)",
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 6,
  },
  tabsNegative: {
    marginHorizontal: -16,
    marginBottom: 24,
  },
  tabs: {
    flexDirection: "row",
    gap: 36,
    paddingLeft: 32,
    paddingRight: 32,
    borderBottomWidth: 2,
    borderBottomColor: "#bfbfbf",
  },
  tab: {
    paddingVertical: 8,
    fontSize: 16,
    fontWeight: "600",
    color: "#555",
    marginBottom: 4,
  },
  tabActive: {
    color: "#000",
    borderBottomWidth: 2,
    borderBottomColor: "#000",
    marginBottom: -2,
  },
  details: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginBottom: 16,
  },
  detailTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  detailTitle: {
    fontSize: 14,
    fontWeight: "500",
    // marginBottom: 4,
    color: "#000",
  },
  detailInfo: {
    fontSize: 14,
    color: "#535353",
  },
  section: {
    marginBottom: 24,
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderRadius: 24,
    backgroundColor: "#fafafa",
    shadowColor: "#000000",
    shadowOpacity: 0.15,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 2,
    gap: 12,
  },
  summary: {
    fontSize: 14,
    lineHeight: 20,
    color: "#000000",
  },
  link: {
    color: "#46AAD8",
    fontSize: 12,
  },
  committee: {
    fontSize: 14,
    fontWeight: "600",
    color: "#000",
  },
  sponsorRow: {
    gap: 4,
  },
  sponsorName: {
    fontSize: 14,
    fontWeight: "600",
    color: "#000",
  },
  sponsorParty: {
    fontSize: 14,
    color: "#535353",
  },
  amendments: {
    fontSize: 14,
    color: "#535353",
  },
  amendmentsSection: {
    borderRadius: 24,
    backgroundColor: "#fafafa",
    shadowColor: "#000000",
    shadowOpacity: 0.15,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 2,
    marginBottom: 96,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 16,
    paddingHorizontal: 16,
  },
  sectionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  amendmentsCount: {
    fontSize: 16,
    fontWeight: "700",
    color: "#000",
  },
  viewAll: {
    fontSize: 12,
    color: "#7B7C81",
  },
  expandedAmendments: {
    paddingHorizontal: 12,
    gap: 16,
    marginBottom: 24,
  },
  amendmentItem: {
    paddingVertical: 12,
    paddingHorizontal: 4,
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#F0F0F0",
  },
  amendmentTitleandSponsor: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  amendmentSponsor: {
    fontSize: 12,
    color: "#535353",
    marginBottom: 4,
  },
  amendmentSummary: {
    fontSize: 14,
    lineHeight: 18,
    color: "#535353",
  },
  sortButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  legislationHeader: {
    paddingHorizontal: 4,
    paddingBottom: 16,
  },
  legislationContainer: {
    paddingHorizontal: 4,
    paddingBottom: 16,
  },

  modalOverlay: {
    flex: 1,
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.2)",
    zIndex: 1000,
  },
  dropdown: {
    backgroundColor: "#f5f5f5",
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 8,
    position: "absolute",
    top: 330,
    right: 16,
    left: 16,
    minWidth: 200,
  },
  dropdownMulti: {
    backgroundColor: "#f5f5f5",
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 8,
    margin: 16,
    marginTop: 180,
  },
  dropdownItem: {
    paddingVertical: 16,
    paddingHorizontal: 16,
  },
  dropdownItemPressed: {
    backgroundColor: "#e0e0e0",
    borderRadius: 12,
    paddingVertical: 16,
    paddingHorizontal: 16,
  },
  dropdownItemText: {
    fontSize: 16,
    color: "#000000",
  },
  dropdownItemTextLabel: {
    fontSize: 16,
    color: "#7B7C81",
    marginTop: 16,
    marginBottom: 6,
    marginHorizontal: 16,
  },
  actionButton: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 6,
    marginLeft: 16,
  },

  // In components.js styles
  officialCard: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 16,
    paddingHorizontal: 14,
    margin: 2,
    borderRadius: 24,
    backgroundColor: "#fafafa",
    marginBottom: 12,
    shadowColor: "#000000",
    shadowOpacity: 0.15,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 2,
  },
  avatar: {
    width: 50,
    height: 50,
    borderRadius: 32,
    marginRight: 12,
    backgroundColor: "#eee",
  },
  cardText: {
    flex: 1,
  },
  name: {
    fontSize: 15,
    color: "#535353",
    fontWeight: "600",
    marginBottom: 2,
  },
  metaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "baseline",
  },
  subtitle: {
    fontSize: 12,
    color: "#7B7C81",
  },
  separator: {
    fontSize: 12,
    color: "#000000",
    marginHorizontal: 4,
  },
  update: {
    fontSize: 12,
    color: "#000000",
    fontWeight: "600",
  },
});
