import { StyleSheet } from "react-native"; // ✅ ADD THIS LINE

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 16,
    backgroundColor: "#fafafa",
  },
  headerBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: 45,
  },
  header: {
    fontSize: 22,
    fontWeight: "600",
    marginBottom: 16,
    marginLeft: 8,
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  headerRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    marginBottom: 16,
  },
  listContent: {
    paddingBottom: 24,
  },
  officialCard: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 16,
    paddingHorizontal: 14,
    // paddingRight: 72,
    margin: 2,
    borderRadius: 24,
    backgroundColor: "#fafafa",
    marginBottom: 12,
    shadowColor: "#000000",
    shadowOpacity: 0.15,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 2,
  },
  avatar: {
    width: 50,
    height: 50,
    borderRadius: 32,
    marginRight: 12,
    backgroundColor: "#eee",
    overflow: "hidden",
  },
  iconText: {
    fontWeight: "600",
  },
  cardText: {
    flex: 1,
  },
  name: {
    fontSize: 15,
    color: "#535353",
    fontWeight: "600",
    marginBottom: 2,
  },
  metaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "baseline",
  },
  subtitle: {
    fontSize: 12,
    color: "#7B7C81",
  },
  separator: {
    fontSize: 12,
    color: "#000000",
    marginHorizontal: 4,
    fontWeight: 900,
  },
  update: {
    fontSize: 12,
    color: "#000000",
    fontWeight: 600,
  },

  modalOverlay: {
    flex: 1,
    // position: "absolute",
    justifyContent: "center",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.2)",
    zIndex: 1000,
  },
  dropdownItem: {
    paddingVertical: 16,
    paddingHorizontal: 16,
  },
  dropdownItemTextLabel: {
    fontSize: 16,
    color: "#7B7C81",
    marginTop: 16,
    marginBottom: 6,
    // marginHorizontal: 16,
  },
  dropdown: {
    backgroundColor: "#fafafa",
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 8,
    marginHorizontal: 16,
    minWidth: 200,
  },
  dropdownItemPressed: {
    backgroundColor: "#e0e0e0",
    borderRadius: 12,
    paddingVertical: 16,
    paddingHorizontal: 16,
  },
  dropdownItemText: {
    fontSize: 16,
    color: "#000000",
  },
  dropdownMulti: {
    backgroundColor: "#fafafa",
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 8,
    margin: 16,
    marginTop: 180,
  },
  dropdownAdd: {
    backgroundColor: "#fafafa",
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 8,
    margin: 16,
    marginTop: 280,
  },
  actionButton: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 6,
    marginLeft: 16,
  },

  subModalCard: {
    backgroundColor: "#fafafa",
    marginHorizontal: 16,
    borderRadius: 12,
    paddingTop: 24,
    paddingHorizontal: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 8,
  },

  actionRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginVertical: 12,
  },

  actionButton: {
    flex: 1,
    paddingVertical: 14,
    alignItems: "center",
    borderRadius: 6,
  },

  verticalDivider: {
    width: 1,
    backgroundColor: "#e0e0e0",
    marginVertical: 12,
  },
});
