import { StyleSheet } from "react-native"; // ✅ ADD THIS LINE

export const styles = StyleSheet.create({
  legislationContainer: {
    paddingBottom: 48,
  },
  billCard: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 16,
    paddingHorizontal: 14,
    margin: 2,
    borderRadius: 24,
    backgroundColor: "#fafafa",
    marginBottom: 12,
    shadowColor: "#000000",
    shadowOpacity: 0.15,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 2,
  },
  billIcon: {
    width: 50,
    height: 50,
    borderRadius: 32,
    backgroundColor: "#eee",
    marginRight: 12,
  },
  billInfo: {
    flex: 1,
    gap: 8,
  },
  billNumber: {
    fontSize: 15,
    color: "#535353",
    fontWeight: "600",
    marginBottom: 2,
  },
  billTitle: {
    fontSize: 14,
    color: "#7B7C81",
  },
  billStatusRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "baseline",
    marginTop: 2,
  },
  separator: {
    fontSize: 12,
    color: "#000000",
    marginHorizontal: 4,
  },
  update: {
    fontSize: 12,
    color: "#000000",
    fontWeight: 600,
  },
  screen: {
    flex: 1,
    backgroundColor: "#fafafa",
  },
  headerBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingTop: 48,
  },
  headerRight: {
    flexDirection: "row",
    gap: 16,
  },
  container: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 24,
    paddingBottom: 48,
    backgroundColor: "#fafafa",
  },
  header: {
    paddingBottom: 16,
    marginHorizontal: 16,
    marginTop: 24,
  },
  roleTop: {
    fontSize: 16,
    color: "#000000",
    fontWeight: "800",
    marginBottom: 24,
    marginLeft: 8,
  },
  centeredRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  avatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
    borderWidth: 4,
    borderColor: "#008CFF",
    overflow: "hidden",
  },
  name: {
    fontSize: 20,
    color: "#000000",
    fontWeight: "800",
    flexShrink: 1,
  },
  tabsNegative: {
    marginHorizontal: 0,
    marginBottom: 24,
  },
  tabs: {
    flexDirection: "row",
    justifyContent: "space-around",
    borderBottomWidth: 2,
    borderBottomColor: "#bfbfbf",
  },
  tab: {
    paddingVertical: 8,
    fontSize: 16,
    fontWeight: "600",
    color: "#555",
    marginBottom: -2,
    height: 42,
  },
  tabActive: {
    color: "#000",
    borderBottomWidth: 1.5,
    borderBottomColor: "#000",
    marginBottom: -1.75,
  },
  bio: {
    fontSize: 14,
    lineHeight: 20,
    color: "#535353",
    marginBottom: 16,
  },
  website: {
    fontSize: 14,
    color: "#46AAD8",
    fontWeight: "500",
    marginBottom: 24,
  },
  section: {
    marginBottom: 24,
    marginHorizontal: 16,
    flexDirection: "column",
    paddingVertical: 0,
    paddingHorizontal: 16,
    borderRadius: 24,
    backgroundColor: "#fafafa",
    shadowColor: "#000000",
    shadowOpacity: 0.15,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 2,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "700",
    marginBottom: -4,
  },
  termRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 16,
  },
  term: {
    fontSize: 14,
    color: "#000",
    fontWeight: "400",
    flex: 1,
  },
  termRole: {
    fontSize: 12,
    color: "#000",
    fontWeight: "500",
    flex: 1,
    textAlign: "right",
  },
  map: {
    width: "100%",
    height: 369,
    borderRadius: 24,
    marginBottom: 96,
    overflow: "hidden",
    shadowColor: "#000000",
    shadowOpacity: 0.15,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 2,
  },
  legislationHeader: {
    paddingHorizontal: 8,
    paddingBottom: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: 48,
    alignItems: "center",
  },
  legislationHeaderTotal: {
    fontWeight: 700,
    fontSize: 16,
    marginRight: 4,
    alignItems: "center",
  },
  legislationHeaderLeft: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  button: {
    flexDirection: "row",
    alignItems: "center",
    minHeight: 40, // Or height: 40, reserves button space
  },
  sortText: {
    fontSize: 13,
    fontWeight: "500",
    color: "#000",
    maxWidth: 84,
    marginRight: 4,
  },
  modalOverlay: {
    flex: 1,
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.2)",
    zIndex: 1000,
  },
  dropdownItem: {
    paddingVertical: 16,
    paddingHorizontal: 16,
  },
  dropdownItemTextLabel: {
    fontSize: 16,
    color: "#7B7C81",
    marginTop: 16,
    marginBottom: 6,
    marginHorizontal: 16,
  },
  dropdown: {
    backgroundColor: "#fafafa",
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 8,
    position: "absolute",
    top: 330,
    right: 16,
    left: 16,
    minWidth: 200,
  },
  dropdownItemPressed: {
    backgroundColor: "#e0e0e0",
    borderRadius: 12,
    paddingVertical: 16,
    paddingHorizontal: 16,
  },
  dropdownItemText: {
    fontSize: 16,
    color: "#000000",
  },
  dropdownMulti: {
    backgroundColor: "#fafafa",
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 8,
    margin: 16,
    marginTop: 180,
  },
  dropdownAdd: {
    backgroundColor: "#fafafa",
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 8,
    margin: 16,
    marginTop: 280,
  },
  actionButton: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 6,
    marginLeft: 16,
  },
  // Add these to the existing StyleSheet.create({ ... })

  officialHeader: {
    alignItems: "center",
    marginBottom: 24,
    paddingVertical: 16,
  },
  avatarLarge: {
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 4,
    borderColor: "#008CFF",
    marginBottom: 16,
  },
  officialName: {
    fontSize: 24,
    fontWeight: "800",
    color: "#000000",
    textAlign: "center",
    marginBottom: 8,
  },
  officialRole: {
    fontSize: 16,
    fontWeight: "600",
    color: "#535353",
    textAlign: "center",
  },
  details: {
    marginBottom: 12,
  },
  detailTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#000000",
    marginBottom: 4,
  },
  detailInfo: {
    fontSize: 14,
    color: "#535353",
    lineHeight: 20,
  },
});
